//! The single C boundary for Tree-sitter. Everything above this file speaks in
//! Skaut-owned types; only the adapter in this directory touches these symbols.

pub const c = @cImport({
    @cInclude("tree_sitter/api.h");
});

/// Entry point generated by the vendored tree-sitter-zig grammar
/// (revision 6479aa13f32f701c383083d8b28360ebd682fb7d, ABI 15).
pub extern fn tree_sitter_zig() callconv(.c) *const c.TSLanguage;

/// Entry points generated by the vendored Markdown block and inline grammars
/// (revision a0a00f817d02412bd92c54d316f164d827b57b5c, ABI 15).
pub extern fn tree_sitter_markdown() callconv(.c) *const c.TSLanguage;
pub extern fn tree_sitter_markdown_inline() callconv(.c) *const c.TSLanguage;
